export const brands = [
  { name: 'MD Decor', en: 'Interior Design', ar: 'تصميم داخلي' },
  { name: 'Interiofy Dubai', en: 'Architect & Design', ar: 'عمارة وتصميم' },
  { name: 'ASAS Contracting LLC', en: 'Building & Interiors', ar: 'بناء وتشطيبات' },
  { name: 'Zero Degree Interior', en: 'Interior Design', ar: 'تصميم داخلي' },
  { name: 'Ahmed Fikry Designs', en: 'Interior Design', ar: 'تصميم داخلي' },
  { name: 'Dewan Architects + Engineers', en: 'Architecture & Engineering', ar: 'عمارة وهندسة' },
  { name: 'AimsHome', en: 'Renovation', ar: 'ترميم' },
  { name: 'Zaitona Technical Services', en: 'Technical Services', ar: 'خدمات فنية' },
  { name: 'Al Layiq Contracting', en: 'General Contracting', ar: 'مقاولات عامة' },
  { name: 'Moonwest Technical Services', en: 'Technical Services', ar: 'خدمات فنية' },
  { name: 'Perfect Creations Interiors', en: 'Interior Design', ar: 'تصميم داخلي' },
  { name: 'A to Z Interior Design', en: 'Interior Design', ar: 'تصميم داخلي' },
  { name: 'Sisters Interior', en: 'Interior Design', ar: 'تصميم داخلي' },
  { name: 'Hox Interiors', en: 'Interior Design', ar: 'تصميم داخلي' },
  { name: 'Fatima Alansari Design', en: 'Design & Execution', ar: 'تصميم وتنفيذ' },
  { name: 'Luna Interiors', en: 'Interior Design', ar: 'تصميم داخلي' },
];

export const AUDIO_SRC =
  'https://base44.app/api/apps/6a3e770029760b0b6cfce316/files/mp/public/6a3e770029760b0b6cfce316/3ee6196fa_ecdf9edde_VideoTestimonial-BustanAlezzLandscapingSharjah.mp3';

export const videos = [
  { id: 'guhev55fj3', aspect: '2.142857142857143' },
  { id: '0f586hyn4f', aspect: '2.2222222222222223' },
  { id: 's6icepjboh', aspect: '1.5384615384615385' },
  { id: '9hkhp8agvo', aspect: '2.2222222222222223' },
];

const en = {
  meta: {
    title: 'RizcoReach | Website Development & SEO Agency in Dubai',
    description:
      'Dubai website development & SEO agency. Fast, custom websites that rank on Google and turn visitors into enquiries, plus Meta & Google Ads for faster leads.',
  },
  hero: {
    label: 'Website Development & SEO Agency — Dubai, UAE',
    title: ['We build websites', 'that <em>rank</em> on Google', '& win you customers.'],
    sub: 'Custom-built, mobile-first websites engineered to be found and designed to convert, backed by SEO and Meta Ads when you need enquiries faster.',
    primary: 'Start your project',
    secondary: 'Free website audit',
    points: ['Custom-built, never a template', 'SEO built in from day one', 'Enquiries are the KPI'],
    stats: [
      { value: '200', suffix: '+', label: 'Businesses served' },
      { value: '4.9', suffix: '★', label: 'Rated on Google' },
      { value: '5', suffix: '+', label: 'Years in the UAE' },
      { value: '100', suffix: '%', label: 'Mobile-first builds' },
    ],
    scroll: 'Scroll',
  },
  marquee: 'Brands we’ve worked with',
  manifesto: {
    label: 'The problem',
    text: 'Most business websites in Dubai look fine and do nothing. Buried on page five of Google. Slow on a phone. No reason to get in touch. Your website should be your best salesperson, working 24/7. That is exactly what we build.',
  },
  services: {
    label: 'Services',
    title: 'Three disciplines.<br/><em>One growth engine.</em>',
    sub: 'A website that wins trust, rankings that bring in customers, and paid ads when you need leads fast. Everything you need to grow online, in one place.',
    items: [
      {
        key: 'web',
        tag: 'The flagship',
        name: 'Website Development',
        desc: 'Beautiful, high-performing websites that don’t just look stunning, they convert visitors into customers. Custom-built by our engineers, lightning-fast, and designed to grow your business.',
        bullets: ['Custom design & development', 'Mobile-first & lightning-fast', 'Built to convert visitors to enquiries', 'Redesigns of existing websites'],
        cta: 'Explore website development',
        href: '/services/website-development',
      },
      {
        key: 'seo',
        tag: 'Compounding growth',
        name: 'Search Engine Optimisation',
        desc: 'Your customers are already searching Google for what you do. We make sure they find you, not your competitors, with the rankings that bring in steady, high-intent enquiries month after month.',
        bullets: ['Technical & on-page SEO', 'Local SEO & Google Business Profile', 'Keyword research & content', 'Clear ranking & traffic reporting'],
        cta: 'Explore SEO',
        href: '/services/seo',
      },
      {
        key: 'ads',
        tag: 'Leads, this month',
        name: 'Meta & Google Ads',
        desc: 'High-converting campaigns on Meta (Facebook & Instagram) and Google that deliver qualified leads, not tire-kickers. Perfect for driving enquiries while your SEO builds, or launching a new site with a bang.',
        bullets: ['Lead generation campaigns', 'Weekly creative refreshes', 'Meta lead centres that qualify', 'Full pipeline transparency'],
        cta: 'Explore Meta & Google Ads',
        href: '/services/meta-ads',
      },
    ],
  },
  pillars: {
    label: 'Why most websites fail',
    title: 'A pretty website<br/>is <em>not</em> enough.',
    sub: 'Your website should be found, load instantly and give every visitor an obvious next step. Here is how we build one.',
    items: [
      {
        t: 'Built to be found from day one',
        d: 'Every page is structured around what your customers actually type into Google, with clean code, proper metadata and local SEO baked in. No relaunching later to fix what should have been done at the start.',
      },
      {
        t: 'Fast on every phone, every time',
        d: 'Most of your visitors are on mobile, and they leave if a page takes more than a few seconds. We design mobile-first and optimise for speed, which keeps customers on the page and helps you rank.',
      },
      {
        t: 'Designed to turn visitors into enquiries',
        d: 'Clear messaging, proof that builds trust, and an obvious next step on every page. WhatsApp, call and enquiry forms placed exactly where people are ready to act.',
      },
    ],
  },
  method: {
    label: 'The RizcoReach Method',
    title: 'Three steps to a website<br/>that works as hard <em>as you do.</em>',
    steps: [
      {
        word: 'Build',
        t: 'The Build',
        d: 'A custom, mobile-first website that tells your story, shows off your best work and makes customers trust you before you’ve even spoken. First impressions win jobs.',
      },
      {
        word: 'Rank',
        t: 'The Rank',
        d: 'Technical SEO, local SEO, Google Business Profile and keyword-led content, so you show up in front of people actively searching for your services right now.',
      },
      {
        word: 'Scale',
        t: 'The Scale',
        d: 'We track, optimise and compound. Rankings climb, traffic grows and enquiries follow. Need results faster? We layer Meta & Google Ads on top.',
      },
    ],
    outcomeLabel: 'The outcome',
    outcome: 'A website that shows up when customers search, and a steady stream of enquiries that comes with it. No slow months, no guessing.',
  },
  results: {
    label: 'Client results',
    title: 'Let the results<br/><em>do the talking.</em>',
    sub: 'Real results from real businesses across Dubai and the UAE. No fluff, just booked jobs and revenue.',
    highlights: [
      { value: '80', suffix: '+', label: 'Qualified leads per month', who: 'Zero Degree Interior' },
      { value: '3', suffix: '×', label: 'Monthly revenue in under 90 days', who: 'Luna Interiors' },
      { value: '100', suffix: '+', label: 'Inquiries for a landscaping brand', who: 'Meta Ads campaign' },
      { value: '60', suffix: '+', label: 'Flooring projects won from 100 leads', who: 'Meta Ads campaign' },
    ],
    testimonials: [
      { industry: 'Interior Design', quote: 'Within 3 weeks we had more inquiries than we could handle. We had to hire two more staff just to manage the volume.', name: 'Maria', company: 'Zero Degree Interior LLC', metric: '80+ qualified leads per month' },
      { industry: 'Landscaping', quote: 'People started recognizing our brand and calling us directly. That never happened before RizcoReach came along.', name: 'Rahat', company: 'Zaitona Landscaping LLC', metric: 'Became the leading landscaping brand in Dubai' },
      { industry: 'Interior Design & Fit-Out', quote: 'The quality of leads is incredible. These are homeowners who are ready to book, not just browsing around.', name: 'Samah', company: 'Interiofy Spaces LLC', metric: 'Booked out 6 weeks in advance' },
      { industry: 'Luxury Interiors', quote: 'We went from slow months to a full project pipeline. The Meta ads RizcoReach runs are truly a different level.', name: 'Ambria', company: 'Luna Interiors', metric: '3× monthly revenue in under 90 days' },
      { industry: 'IT & Software', quote: 'We went from cold outreach to a steady inbound pipeline. The quality of B2B leads is night and day compared to what we were getting before.', name: 'Omar', company: 'NexusTech Solutions LLC', metric: '35+ qualified B2B leads per month' },
      { industry: 'Healthcare & Clinics', quote: 'Our appointment calendar is finally full with the right kind of patients. RizcoReach understood our practice and targeted exactly who we needed.', name: 'Dr. Sara', company: 'Elite Aesthetic Clinic LLC', metric: '60+ patient bookings per month' },
      { industry: 'Fitness & Pilates', quote: 'Our trial-to-membership conversion doubled. RizcoReach built a funnel that brings in people who are actually ready to commit, not just browsing.', name: 'Layla', company: 'CorePilates Studio LLC', metric: '50+ new member signups in 90 days' },
      { industry: 'Corporate Services', quote: 'We were spending on ads with zero ROI. RizcoReach rebuilt our entire funnel and within 3 months we had a predictable pipeline of corporate clients.', name: 'Ahmed', company: 'Prime Advisory LLC', metric: '20+ corporate client enquiries per month' },
    ],
    audio: {
      label: 'Client testimonial',
      title: 'Hear it from our clients.',
      name: 'Mohd Al Battrawi',
      company: 'Bustan Al-Ezz Landscaping · Sharjah, UAE',
      deliveredLabel: 'What we delivered',
      delivered: ['Consistent qualified leads every month', 'Full Meta Ads setup and management', 'Scroll-stopping creative production', 'Real growth, not just clicks'],
      quote: 'One of the leads we got through our Instagram and Facebook ads decided to work with us. Let’s keep getting more leads and more clients.',
      listen: 'Listen to the testimonial',
    },
  },
  cases: {
    label: 'Paid ads · Case studies',
    title: 'Need leads now?<br/><em>Watch our campaigns in action.</em>',
    sub: 'SEO compounds over time. When you need enquiries this month, our Meta & Google Ads team delivers. These are real campaigns and lead centres we’ve run for home improvement businesses across the UAE.',
    items: [
      { tag: 'Landscaping · Campaign', t: 'How we generated 100+ inquiries for a Dubai landscaping business', d: 'The exact Meta Ads structure, creatives and targeting that turned ad spend into a flood of qualified leads.', stats: [{ v: '100+', l: 'Total inquiries' }, { v: '50+', l: 'Qualified leads' }, { v: '75k+', l: 'AED revenue pipeline' }] },
      { tag: 'Landscaping · Lead centre', t: 'Inside the Meta lead centre that kept this landscaper fully booked', d: 'How we capture, qualify and deliver homeowner leads in real time, so our client never chases a cold contact again.', stats: [{ v: '100+', l: 'Total inquiries' }, { v: '50+', l: 'Qualified leads' }] },
      { tag: 'Flooring · Campaign', t: '100 leads for a UAE flooring business: the exact campaign', d: 'A system that generated 100 qualified leads, with over 60 of them converting into successful flooring projects.', stats: [{ v: '100', l: 'Leads generated' }, { v: '60+', l: 'Successful projects' }] },
      { tag: 'Flooring · Lead centre', t: 'Inside the lead centre behind 60+ successful flooring projects', d: 'The structure that captures, qualifies and delivers homeowner leads straight to the team. No cold outreach, no wasted follow-ups.', stats: [{ v: '100', l: 'Leads generated' }, { v: '60+', l: 'Successful projects' }] },
    ],
    play: 'Play case study',
    cta: 'Get a campaign plan for your business',
  },
  tools: {
    label: 'Free growth tools',
    title: 'Useful before<br/><em>you even call us.</em>',
    sub: 'The same tools we use to scope projects, free for you. Audit your website, model what page one is worth, plan your ad budget and scope your new site.',
    items: [
      { key: 'audit', t: 'Website Audit', d: 'Instant SEO, speed and conversion check for any URL.', href: '/tools/website-audit', icon: 'gauge', cta: 'Run audit' },
      { key: 'seo', t: 'SEO Revenue Calculator', d: 'See what ranking on page one is worth to your business.', href: '/tools/seo-calculator', icon: 'trending', cta: 'Calculate' },
      { key: 'ads', t: 'Meta Ads Calculator', d: 'Forecast leads, cost per lead and ROAS from your budget.', href: '/tools/meta-ads-calculator', icon: 'target', cta: 'Forecast' },
      { key: 'est', t: 'Website Project Estimator', d: 'Scope pages, features and timeline for your new website.', href: '/tools/website-estimator', icon: 'sliders', cta: 'Plan my site' },
    ],
  },
  industries: {
    label: 'Industries we serve',
    title: 'Where our strategy<br/><em>has delivered.</em>',
    sub: 'We go deep in specific verticals, and that is exactly why we get results.',
    view: 'View',
  },
  about: {
    label: 'About RizcoReach',
    title: 'Built in Dubai.<br/><em>Built to be found.</em>',
    paras: [
      'RizcoReach is a Dubai-based website development and SEO agency. We work with ambitious SMEs across the UAE to design fast, custom websites and get them ranking on Google for the searches that bring in real customers. When a business needs leads faster, our performance marketing team runs Meta and Google Ads on top.',
      'We have worked with construction firms, IT companies, clinics, fitness studios, corporate service providers and many more. The pattern is always the same: great businesses hidden behind slow, outdated websites that nobody can find. They leave with a website that reflects the quality of their work, and shows up when customers search.',
    ],
    tags: ['Dubai based', 'SME growth', 'Website development', 'SEO specialists', 'Local SEO', 'Meta & Google Ads', 'UAE & GCC', '5+ years experience'],
    officeLabel: 'Studio',
    office: 'Latifa Tower, Sheikh Zayed Road, Dubai',
  },
  process: {
    label: 'How it works',
    title: 'Simple start.<br/><em>Serious results.</em>',
    sub: 'Getting started takes 15 minutes. From there, we handle the design, the build, the launch and the rankings.',
    steps: [
      { t: 'Fill out the inquiry form', d: 'Tell us about your business, your current website and your goals. It takes about 3 minutes.' },
      { t: 'Discovery call (30 min)', d: 'An honest conversation to understand where you are today. No pitch, no pressure. Just finding out if we’re the right fit.' },
      { t: 'Website & SEO plan', d: 'We review your site and search visibility, research what your customers search for, and map the pages, design direction and SEO plan with a clear quote.' },
      { t: 'Build, launch and rank', d: 'You review at every stage, we launch with SEO foundations in place, then keep improving your rankings so the enquiries keep coming.' },
    ],
  },
  notfit: {
    label: 'Honesty first',
    title: 'Where we are <em>not</em><br/>the right fit.',
    sub: 'We would rather say this upfront than waste your time or ours.',
    items: [
      { t: 'Large corporates', d: 'We work with SMEs and founder-led businesses, not large corporates with committee decisions.' },
      { t: 'Cheapest template sites', d: 'If you want the cheapest template you can find, we are not aligned. We build websites as business assets.' },
      { t: 'Overnight SEO promises', d: 'SEO is a compounding investment. Anyone promising page one by next week is selling you something risky.' },
      { t: 'Weak underlying service', d: 'More traffic will not fix a weak service, it will expose it faster.' },
      { t: 'Nobody to follow up', d: 'If no one in your team can respond to enquiries and close them, a better website just creates frustration.' },
      { t: 'No capacity to deliver', d: 'If you cannot handle more work right now, wait until you can. We scale what is already working.' },
    ],
  },
  faq: {
    label: 'FAQ',
    title: 'Questions we get<br/><em>all the time.</em>',
    more: 'Still have a question?',
    moreCta: 'Ask us directly',
    items: [
      { q: 'What industries do you work with?', a: 'Ambitious SMEs across construction and home improvement, IT and software, healthcare and clinics, fitness and pilates, corporate services and accounting, landscaping, permanent makeup and aesthetics, and professional B2B services. If you are a growing UAE business that needs a better website or more visibility on Google, we can likely help.' },
      { q: 'How are you different from a typical web design agency?', a: 'Most web designers hand over a nice-looking site and consider the job done. We care about what happens after launch. Does it show up on Google? Does it load fast on a phone? Does it turn visitors into enquiries? We build the whole journey, from the first search to the moment a customer gets in touch.' },
      { q: 'How much does a website cost?', a: 'Every website is quoted to its scope. A focused business website is very different from a large site with booking systems, e-commerce or custom features. On our first call we understand what you need and give you a clear quote before any work begins. If the numbers do not make sense for you, we will say so.' },
      { q: 'How long does SEO take to work?', a: 'SEO compounds over time. Technical fixes and Google Business Profile improvements can show movement within weeks, while competitive keywords usually take a few months of consistent work. We set realistic expectations and report on rankings, traffic and enquiries so you always know where you stand.' },
      { q: 'I already have a website. Can you improve it?', a: 'Yes. We review what you have, what is performing and what is not, and find the fastest path to better results. Sometimes it is a speed and SEO fix. Sometimes a full redesign is the better investment. We will be honest about what needs to change.' },
      { q: 'Do you still run Meta and Google Ads?', a: 'Absolutely. Paid ads are a core service. Many clients pair a new website with Meta or Google Ads to bring in enquiries straight away while their SEO builds.' },
      { q: 'What does onboarding look like?', a: 'After our strategy call we collect your brand assets and content, agree the page structure and design direction, then start building. You review and give feedback at each stage before anything goes live. Once launched, we set up analytics and Google Search Console and begin the ongoing SEO work.' },
      { q: 'Do you build websites in Arabic?', a: 'Yes. We build fully bilingual English and Arabic websites with proper right-to-left layouts, Arabic typography and SEO for both languages.' },
    ],
  },
};

const ar: typeof en = {
  meta: {
    title: 'RizcoReach | وكالة تطوير مواقع وتحسين محركات البحث في دبي',
    description:
      'وكالة تطوير مواقع وتحسين محركات بحث في دبي. مواقع سريعة ومخصّصة تتصدّر جوجل وتحوّل الزوار إلى طلبات، مع إعلانات ميتا وجوجل لعملاء أسرع.',
  },
  hero: {
    label: 'وكالة تطوير مواقع وتحسين محركات البحث — دبي، الإمارات',
    title: ['نبني مواقع إلكترونية', '<em>تتصدّر</em> نتائج جوجل', 'وتجلب لك العملاء.'],
    sub: 'مواقع مخصّصة تُبنى للجوال أولاً، مُهندَسة لتظهر في البحث ومصمّمة لتحقّق التحويل، مدعومة بتحسين محركات البحث وإعلانات ميتا عندما تحتاج طلبات أسرع.',
    primary: 'ابدأ مشروعك',
    secondary: 'فحص مجاني لموقعك',
    points: ['تصميم مخصّص، لا قوالب جاهزة', 'تحسين البحث مدمج من اليوم الأول', 'الطلبات هي مقياس النجاح'],
    stats: [
      { value: '200', suffix: '+', label: 'عميل خدمناه' },
      { value: '4.9', suffix: '★', label: 'تقييمنا على جوجل' },
      { value: '5', suffix: '+', label: 'سنوات في الإمارات' },
      { value: '100', suffix: '%', label: 'مواقع للجوال أولاً' },
    ],
    scroll: 'مرّر',
  },
  marquee: 'علامات تجارية عملنا معها',
  manifesto: {
    label: 'المشكلة',
    text: 'معظم مواقع الشركات في دبي تبدو جيدة لكنها لا تحقّق شيئاً. مدفونة في الصفحة الخامسة من جوجل. بطيئة على الجوال. ولا سبب يدفع الزائر للتواصل. يجب أن يكون موقعك أفضل مندوب مبيعات لديك، يعمل على مدار الساعة. وهذا تحديداً ما نبنيه.',
  },
  services: {
    label: 'الخدمات',
    title: 'ثلاث تخصّصات.<br/><em>محرّك نموّ واحد.</em>',
    sub: 'موقع يكسب الثقة، وترتيب في البحث يجلب العملاء، وإعلانات مدفوعة عندما تحتاج نتائج سريعة. كل ما تحتاجه للنمو رقمياً في مكان واحد.',
    items: [
      {
        key: 'web',
        tag: 'خدمتنا الرئيسية',
        name: 'تطوير المواقع الإلكترونية',
        desc: 'مواقع جميلة وعالية الأداء لا تكتفي بالمظهر المبهر، بل تحوّل الزوار إلى عملاء. يبنيها مهندسونا خصيصاً لك، فائقة السرعة ومصمّمة لتنمية أعمالك.',
        bullets: ['تصميم وتطوير مخصّص', 'للجوال أولاً وبسرعة فائقة', 'مبني لتحويل الزوار إلى طلبات', 'إعادة تصميم المواقع الحالية'],
        cta: 'اكتشف تطوير المواقع',
        href: '/services/website-development',
      },
      {
        key: 'seo',
        tag: 'نموّ متراكم',
        name: 'تحسين محركات البحث',
        desc: 'عملاؤك يبحثون على جوجل عمّا تقدّمه الآن. نتأكد أنهم يجدونك أنت لا منافسيك، بترتيب يجلب طلبات ثابتة عالية النية شهراً بعد شهر.',
        bullets: ['تحسين تقني وداخلي للصفحات', 'السيو المحلي وملف جوجل التجاري', 'بحث الكلمات المفتاحية والمحتوى', 'تقارير واضحة للترتيب والزيارات'],
        cta: 'اكتشف خدمة السيو',
        href: '/services/seo',
      },
      {
        key: 'ads',
        tag: 'عملاء هذا الشهر',
        name: 'إعلانات ميتا وجوجل',
        desc: 'حملات عالية التحويل على ميتا (فيسبوك وإنستغرام) وجوجل تجلب عملاء مؤهَّلين لا متصفّحين عابرين. مثالية لجلب الطلبات بينما يُبنى ترتيبك، أو لإطلاق موقع جديد بقوة.',
        bullets: ['حملات استقطاب العملاء', 'تحديث أسبوعي للتصاميم الإعلانية', 'مراكز عملاء على ميتا تؤهّل الطلبات', 'شفافية كاملة في مسار المبيعات'],
        cta: 'اكتشف إعلانات ميتا وجوجل',
        href: '/services/meta-ads',
      },
    ],
  },
  pillars: {
    label: 'لماذا تفشل معظم المواقع',
    title: 'الموقع الجميل<br/><em>لا يكفي.</em>',
    sub: 'يجب أن يظهر موقعك في البحث، ويُحمَّل فوراً، ويمنح كل زائر خطوة تالية واضحة. هكذا نبنيه.',
    items: [
      {
        t: 'مبني ليظهر في البحث من اليوم الأول',
        d: 'كل صفحة تُبنى حول ما يكتبه عملاؤك فعلاً في جوجل، بكود نظيف وبيانات وصفية صحيحة وسيو محلي مدمج. لا حاجة لإعادة الإطلاق لاحقاً لإصلاح ما كان يجب فعله من البداية.',
      },
      {
        t: 'سريع على كل جوال، في كل مرة',
        d: 'معظم زوارك على الجوال، ويغادرون إن تأخرت الصفحة أكثر من ثوانٍ. نصمّم للجوال أولاً ونحسّن السرعة، ما يُبقي العملاء في الصفحة ويرفع ترتيبك.',
      },
      {
        t: 'مصمّم لتحويل الزوار إلى طلبات',
        d: 'رسائل واضحة، وأدلّة تبني الثقة، وخطوة تالية واضحة في كل صفحة. واتساب والاتصال ونماذج الطلب في المكان الذي يكون فيه الزائر جاهزاً للتواصل.',
      },
    ],
  },
  method: {
    label: 'منهجية RizcoReach',
    title: 'ثلاث خطوات لموقع<br/><em>يعمل بجدّ مثلك.</em>',
    steps: [
      { word: 'البناء', t: 'البناء', d: 'موقع مخصّص للجوال أولاً يروي قصتك ويعرض أفضل أعمالك ويجعل العملاء يثقون بك قبل أن تتحدثوا. الانطباع الأول يربح المشاريع.' },
      { word: 'الترتيب', t: 'الترتيب', d: 'سيو تقني ومحلي وملف جوجل التجاري ومحتوى مبني على الكلمات المفتاحية، لتظهر أمام من يبحثون عن خدماتك الآن.' },
      { word: 'التوسّع', t: 'التوسّع', d: 'نتتبّع ونحسّن ونراكم. يرتفع الترتيب وتزداد الزيارات وتتبعها الطلبات. تحتاج نتائج أسرع؟ نضيف إعلانات ميتا وجوجل.' },
    ],
    outcomeLabel: 'النتيجة',
    outcome: 'موقع يظهر عندما يبحث العملاء، وتدفّق ثابت من الطلبات يأتي معه. لا أشهر هادئة، ولا تخمين.',
  },
  results: {
    label: 'نتائج العملاء',
    title: 'دع النتائج<br/><em>تتحدث عنّا.</em>',
    sub: 'نتائج حقيقية لشركات حقيقية في دبي والإمارات. بلا مبالغة، مجرد مشاريع محجوزة وإيرادات.',
    highlights: [
      { value: '80', suffix: '+', label: 'عميل مؤهَّل شهرياً', who: 'Zero Degree Interior' },
      { value: '3', suffix: '×', label: 'الإيرادات الشهرية خلال أقل من 90 يوماً', who: 'Luna Interiors' },
      { value: '100', suffix: '+', label: 'استفسار لعلامة تنسيق حدائق', who: 'حملة إعلانات ميتا' },
      { value: '60', suffix: '+', label: 'مشروع أرضيات من 100 عميل', who: 'حملة إعلانات ميتا' },
    ],
    testimonials: [
      { industry: 'تصميم داخلي', quote: 'خلال 3 أسابيع وصلتنا استفسارات أكثر مما نستطيع التعامل معه. اضطررنا لتوظيف شخصين إضافيين لإدارة الطلبات.', name: 'ماريا', company: 'Zero Degree Interior LLC', metric: 'أكثر من 80 عميل مؤهَّل شهرياً' },
      { industry: 'تنسيق حدائق', quote: 'بدأ الناس يتعرّفون على علامتنا ويتصلون بنا مباشرة. لم يحدث ذلك قبل RizcoReach.', name: 'رحات', company: 'Zaitona Landscaping LLC', metric: 'أصبحت العلامة الرائدة في تنسيق الحدائق بدبي' },
      { industry: 'تصميم داخلي وتشطيبات', quote: 'جودة العملاء مذهلة. أصحاب منازل جاهزون للحجز، لا مجرد متصفّحين.', name: 'سماح', company: 'Interiofy Spaces LLC', metric: 'محجوزون لمدة 6 أسابيع مقدماً' },
      { industry: 'تصميم داخلي فاخر', quote: 'انتقلنا من أشهر هادئة إلى قائمة مشاريع ممتلئة. إعلانات ميتا التي تديرها RizcoReach في مستوى مختلف تماماً.', name: 'أمبريا', company: 'Luna Interiors', metric: '3 أضعاف الإيرادات الشهرية خلال أقل من 90 يوماً' },
      { industry: 'تقنية المعلومات والبرمجيات', quote: 'انتقلنا من التواصل البارد إلى تدفّق ثابت من الطلبات الواردة. جودة عملاء الشركات مختلفة تماماً عمّا كنّا نحصل عليه.', name: 'عمر', company: 'NexusTech Solutions LLC', metric: 'أكثر من 35 عميل شركات مؤهَّل شهرياً' },
      { industry: 'الرعاية الصحية والعيادات', quote: 'جدول مواعيدنا ممتلئ أخيراً بالمرضى المناسبين. فهمت RizcoReach طبيعة عيادتنا واستهدفت من نحتاجهم بالضبط.', name: 'د. سارة', company: 'Elite Aesthetic Clinic LLC', metric: 'أكثر من 60 حجز مريض شهرياً' },
      { industry: 'اللياقة والبيلاتس', quote: 'تضاعف تحويل التجارب إلى اشتراكات. بنت RizcoReach مساراً يجلب أشخاصاً جاهزين فعلاً للالتزام.', name: 'ليلى', company: 'CorePilates Studio LLC', metric: 'أكثر من 50 مشترك جديد خلال 90 يوماً' },
      { industry: 'خدمات الشركات', quote: 'كنا ننفق على الإعلانات دون أي عائد. أعادت RizcoReach بناء مسارنا بالكامل، وخلال 3 أشهر أصبح لدينا تدفّق ثابت من عملاء الشركات.', name: 'أحمد', company: 'Prime Advisory LLC', metric: 'أكثر من 20 استفسار من الشركات شهرياً' },
    ],
    audio: {
      label: 'شهادة عميل',
      title: 'اسمعها من عملائنا.',
      name: 'محمد البطراوي',
      company: 'بستان العز لتنسيق الحدائق · الشارقة، الإمارات',
      deliveredLabel: 'ما قدّمناه',
      delivered: ['عملاء مؤهَّلون بانتظام كل شهر', 'إعداد وإدارة كاملة لإعلانات ميتا', 'إنتاج تصاميم إعلانية تلفت الانتباه', 'نموّ حقيقي، لا مجرد نقرات'],
      quote: 'أحد العملاء الذين وصلونا عبر إعلانات إنستغرام وفيسبوك قرر العمل معنا. لنواصل الحصول على مزيد من الطلبات والعملاء.',
      listen: 'استمع إلى الشهادة',
    },
  },
  cases: {
    label: 'الإعلانات المدفوعة · دراسات حالة',
    title: 'تحتاج عملاء الآن؟<br/><em>شاهد حملاتنا على أرض الواقع.</em>',
    sub: 'السيو يتراكم مع الوقت. وعندما تحتاج طلبات هذا الشهر، يتولّى فريق إعلانات ميتا وجوجل المهمة. هذه حملات ومراكز عملاء حقيقية أدرناها لشركات تحسين منازل في الإمارات.',
    items: [
      { tag: 'تنسيق حدائق · حملة', t: 'كيف حققنا أكثر من 100 استفسار لشركة تنسيق حدائق في دبي', d: 'هيكل حملة ميتا والتصاميم والاستهداف الذي حوّل الإنفاق الإعلاني إلى سيل من العملاء المؤهَّلين.', stats: [{ v: '+100', l: 'إجمالي الاستفسارات' }, { v: '+50', l: 'عميل مؤهَّل' }, { v: '+75 ألف', l: 'درهم في قائمة الإيرادات' }] },
      { tag: 'تنسيق حدائق · مركز العملاء', t: 'داخل مركز العملاء على ميتا الذي أبقى هذه الشركة محجوزة بالكامل', d: 'كيف نلتقط طلبات أصحاب المنازل ونؤهّلها ونسلّمها لحظياً، فلا يطارد عميلنا جهة اتصال باردة مجدداً.', stats: [{ v: '+100', l: 'إجمالي الاستفسارات' }, { v: '+50', l: 'عميل مؤهَّل' }] },
      { tag: 'أرضيات · حملة', t: '100 عميل لشركة أرضيات إماراتية: الحملة بالتفصيل', d: 'نظام جلب 100 عميل مؤهَّل، تحوّل أكثر من 60 منهم إلى مشاريع أرضيات ناجحة.', stats: [{ v: '100', l: 'عميل' }, { v: '+60', l: 'مشروع ناجح' }] },
      { tag: 'أرضيات · مركز العملاء', t: 'داخل مركز العملاء وراء أكثر من 60 مشروع أرضيات ناجح', d: 'الهيكل الذي يلتقط طلبات أصحاب المنازل ويؤهّلها ويسلّمها مباشرة للفريق. بلا تواصل بارد ولا متابعات مهدرة.', stats: [{ v: '100', l: 'عميل' }, { v: '+60', l: 'مشروع ناجح' }] },
    ],
    play: 'تشغيل دراسة الحالة',
    cta: 'احصل على خطة حملة لعملك',
  },
  tools: {
    label: 'أدوات نموّ مجانية',
    title: 'مفيدة حتى<br/><em>قبل أن تتصل بنا.</em>',
    sub: 'الأدوات نفسها التي نستخدمها لتقدير المشاريع، مجاناً لك. افحص موقعك، واحسب قيمة الصفحة الأولى، وخطّط ميزانية إعلاناتك، وحدّد نطاق موقعك الجديد.',
    items: [
      { key: 'audit', t: 'فحص الموقع الإلكتروني', d: 'فحص فوري للسيو والسرعة والتحويل لأي رابط.', href: '/tools/website-audit', icon: 'gauge', cta: 'ابدأ الفحص' },
      { key: 'seo', t: 'حاسبة عائد السيو', d: 'اعرف قيمة تصدّر الصفحة الأولى لعملك.', href: '/tools/seo-calculator', icon: 'trending', cta: 'احسب' },
      { key: 'ads', t: 'حاسبة إعلانات ميتا', d: 'توقّع العملاء وتكلفة العميل والعائد من ميزانيتك.', href: '/tools/meta-ads-calculator', icon: 'target', cta: 'توقّع' },
      { key: 'est', t: 'مُخطِّط مشروع الموقع', d: 'حدّد الصفحات والميزات والجدول الزمني لموقعك الجديد.', href: '/tools/website-estimator', icon: 'sliders', cta: 'خطّط موقعي' },
    ],
  },
  industries: {
    label: 'القطاعات التي نخدمها',
    title: 'حيث حقّقت<br/><em>استراتيجيتنا النتائج.</em>',
    sub: 'نتعمّق في قطاعات محددة، وهذا بالضبط سبب نتائجنا.',
    view: 'عرض',
  },
  about: {
    label: 'عن RizcoReach',
    title: 'صُنعت في دبي.<br/><em>صُنعت لتُرى.</em>',
    paras: [
      'RizcoReach وكالة تطوير مواقع إلكترونية وتحسين محركات بحث مقرّها دبي. نعمل مع الشركات الصغيرة والمتوسطة الطموحة في الإمارات لتصميم مواقع سريعة ومخصّصة وتصدّر نتائج جوجل في عمليات البحث التي تجلب عملاء حقيقيين. وعندما تحتاج الشركة عملاء أسرع، يدير فريق التسويق بالأداء لدينا إعلانات ميتا وجوجل.',
      'عملنا مع شركات مقاولات وتقنية وعيادات واستوديوهات لياقة ومزوّدي خدمات شركات وغيرهم الكثير. والنمط دائماً واحد: شركات ممتازة مختبئة خلف مواقع بطيئة وقديمة لا يجدها أحد. ويخرجون بموقع يعكس جودة عملهم ويظهر عندما يبحث العملاء.',
    ],
    tags: ['مقرّنا دبي', 'نموّ الشركات', 'تطوير المواقع', 'متخصّصو السيو', 'السيو المحلي', 'إعلانات ميتا وجوجل', 'الإمارات والخليج', '+5 سنوات خبرة'],
    officeLabel: 'الاستوديو',
    office: 'برج لطيفة، شارع الشيخ زايد، دبي',
  },
  process: {
    label: 'كيف نعمل',
    title: 'بداية بسيطة.<br/><em>نتائج جادّة.</em>',
    sub: 'البدء يستغرق 15 دقيقة. بعدها نتولّى التصميم والبناء والإطلاق والترتيب.',
    steps: [
      { t: 'املأ نموذج الطلب', d: 'أخبرنا عن عملك وموقعك الحالي وأهدافك. يستغرق نحو 3 دقائق.' },
      { t: 'مكالمة استكشافية (30 دقيقة)', d: 'محادثة صريحة لفهم وضعك الحالي. بلا عروض بيع ولا ضغط، فقط لنعرف إن كنا الخيار المناسب.' },
      { t: 'خطة الموقع والسيو', d: 'نراجع موقعك وظهورك في البحث، ونبحث عمّا يبحث عنه عملاؤك، ونرسم الصفحات واتجاه التصميم وخطة السيو مع عرض سعر واضح.' },
      { t: 'البناء والإطلاق والتصدّر', d: 'تراجع كل مرحلة، ونطلق الموقع بأسس سيو متينة، ثم نواصل تحسين ترتيبك لتستمر الطلبات.' },
    ],
  },
  notfit: {
    label: 'الصراحة أولاً',
    title: 'متى <em>لا</em> نكون<br/>الخيار المناسب.',
    sub: 'نفضّل أن نقول هذا من البداية بدلاً من إضاعة وقتك أو وقتنا.',
    items: [
      { t: 'الشركات الكبرى', d: 'نعمل مع الشركات الصغيرة والمتوسطة والشركات التي يقودها مؤسسوها، لا مع الشركات الكبرى ذات القرارات عبر اللجان.' },
      { t: 'أرخص المواقع الجاهزة', d: 'إن كنت تريد أرخص قالب ممكن، فلسنا الخيار المناسب. نبني المواقع كأصول تجارية.' },
      { t: 'وعود السيو بين ليلة وضحاها', d: 'السيو استثمار متراكم. من يعدك بالصفحة الأولى الأسبوع القادم يبيعك شيئاً محفوفاً بالمخاطر.' },
      { t: 'خدمة أساسية ضعيفة', d: 'المزيد من الزيارات لن يُصلح خدمة ضعيفة، بل سيكشفها أسرع.' },
      { t: 'لا أحد للمتابعة', d: 'إن لم يكن في فريقك من يردّ على الطلبات ويُغلق الصفقات، فالموقع الأفضل سيخلق الإحباط فقط.' },
      { t: 'لا قدرة على التنفيذ', d: 'إن لم تكن قادراً على استيعاب مزيد من العمل الآن، فانتظر حتى تستطيع. نحن نوسّع ما ينجح بالفعل.' },
    ],
  },
  faq: {
    label: 'الأسئلة الشائعة',
    title: 'أسئلة تصلنا<br/><em>باستمرار.</em>',
    more: 'لديك سؤال آخر؟',
    moreCta: 'اسألنا مباشرة',
    items: [
      { q: 'مع أي القطاعات تعملون؟', a: 'نعمل مع الشركات الصغيرة والمتوسطة الطموحة في المقاولات وتحسين المنازل، وتقنية المعلومات والبرمجيات، والرعاية الصحية والعيادات، واللياقة والبيلاتس، وخدمات الشركات والمحاسبة، وتنسيق الحدائق، والمكياج الدائم والتجميل، والخدمات المهنية. إن كنت شركة نامية في الإمارات تحتاج موقعاً أفضل أو ظهوراً أكبر على جوجل، فغالباً نستطيع مساعدتك.' },
      { q: 'بماذا تختلفون عن وكالات تصميم المواقع التقليدية؟', a: 'معظم المصمّمين يسلّمون موقعاً جميلاً ويعتبرون المهمة منتهية. نحن نهتم بما يحدث بعد الإطلاق: هل يظهر على جوجل؟ هل يُحمَّل بسرعة على الجوال؟ هل يحوّل الزوار إلى طلبات؟ نبني الرحلة كاملة من أول بحث حتى لحظة تواصل العميل.' },
      { q: 'كم تكلفة الموقع الإلكتروني؟', a: 'كل موقع يُسعَّر حسب نطاقه. موقع الأعمال المركّز يختلف كثيراً عن موقع كبير بأنظمة حجز أو متجر إلكتروني أو ميزات مخصّصة. في مكالمتنا الأولى نفهم احتياجك ونقدّم عرض سعر واضحاً قبل بدء أي عمل. وإن لم تكن الأرقام منطقية لك، سنقول ذلك بصراحة.' },
      { q: 'متى تظهر نتائج السيو؟', a: 'السيو يتراكم مع الوقت. الإصلاحات التقنية وتحسين ملف جوجل التجاري قد تُظهر تقدّماً خلال أسابيع، بينما تحتاج الكلمات التنافسية عادةً بضعة أشهر من العمل المستمر. نضع توقعات واقعية ونقدّم تقارير عن الترتيب والزيارات والطلبات لتعرف موقعك دائماً.' },
      { q: 'لدي موقع بالفعل، هل يمكنكم تحسينه؟', a: 'نعم. نراجع ما لديك، وما يعمل وما لا يعمل، ونجد أسرع طريق لنتائج أفضل. أحياناً يكفي إصلاح السرعة والسيو، وأحياناً تكون إعادة التصميم الكاملة الاستثمار الأفضل. وسنكون صريحين فيما يحتاج للتغيير.' },
      { q: 'هل ما زلتم تديرون إعلانات ميتا وجوجل؟', a: 'بالتأكيد. الإعلانات المدفوعة خدمة أساسية لدينا. كثير من العملاء يجمعون بين موقع جديد وإعلانات ميتا أو جوجل لجلب الطلبات فوراً بينما يُبنى ترتيبهم في البحث.' },
      { q: 'كيف تبدو مرحلة البدء؟', a: 'بعد مكالمة الاستراتيجية نجمع أصول علامتك ومحتواك، ونتفق على هيكل الصفحات واتجاه التصميم، ثم نبدأ البناء. تراجع وتبدي ملاحظاتك في كل مرحلة قبل أن يُنشر أي شيء. وبعد الإطلاق نُعدّ التحليلات وGoogle Search Console ونبدأ العمل المستمر على السيو.' },
      { q: 'هل تبنون مواقع باللغة العربية؟', a: 'نعم. نبني مواقع ثنائية اللغة بالكامل بالعربية والإنجليزية، بتخطيط صحيح من اليمين لليسار، وخطوط عربية أنيقة، وسيو للّغتين.' },
    ],
  },
};

export const home = { en, ar };
