const en = {
  primary: 'Schedule your free consultation',
  secondary: 'Free website audit',
  resultsLabel: 'Real results',
  resultsTitle: 'What our clients say',
  whoLabel: 'Who we help',
  whoTitle: 'The businesses<br/><em>we get results for.</em>',
  whoSub: 'We work with businesses that have a strong service and real ambition to grow. Here’s who we typically work with in this space.',
  mistakesLabel: 'Common pitfalls',
  mistakesTitle: 'The 3 mistakes<br/><em>keeping you stuck.</em>',
  mistakesSub: 'Before we build or launch anything, we fix the problems that silently kill most websites and ad spend.',
  systemLabel: 'Your growth system',
  systemTitle: 'Website, SEO and ads,<br/><em>working as one.</em>',
  system: (aud: string) => [
    { key: 'web', icon: 'monitor', t: 'A website that wins trust', d: `A fast, premium website built around what ${aud} need to see before they get in touch.`, href: '/services/website-development' },
    { key: 'seo', icon: 'search', t: 'Rank where they search', d: `Local SEO and service pages that put you in front of ${aud} searching on Google right now.`, href: '/services/seo' },
    { key: 'ads', icon: 'megaphone', t: 'Leads this month', d: `Meta and Google campaigns that bring qualified ${aud} while your rankings compound.`, href: '/services/meta-ads' },
  ],
  expectLabel: 'What you can expect',
  expectTitle: 'When we<br/><em>work together.</em>',
  whyLabel: 'Why RizcoReach',
  why: [
    { k: 'AED 5M+', t: 'UAE market expertise', d: 'We’ve invested over AED 5M in paid media across Dubai and the GCC. We know what converts in this market.' },
    { k: 'Monthly', t: 'No lock-in contracts', d: 'We work month-to-month. Our results keep you, not a contract.' },
    { k: 'Niche', t: 'Vertical specialisation', d: 'We don’t work with everyone. That focus means faster results and sharper work for your niche.' },
  ],
  stepsLabel: 'Next steps',
  stepsTitle: 'How it<br/><em>works.</em>',
  steps: [
    { t: 'Apply for a consultation', d: 'Fill in a short form so we can understand your business, your goals, and whether we’re the right fit for each other.' },
    { t: 'Strategy call', d: 'We map out exactly how we’d approach your market, what we’d build, and what results you can expect.' },
    { t: 'We go live', d: 'Your website, SEO and campaigns are built, launched and optimised. You focus on the customers.' },
  ],
  otherLabel: 'Other industries',
  learn: 'Learn more',
};

const ar: typeof en = {
  primary: 'احجز استشارتك المجانية',
  secondary: 'فحص مجاني لموقعك',
  resultsLabel: 'نتائج حقيقية',
  resultsTitle: 'ماذا يقول عملاؤنا',
  whoLabel: 'من نساعد',
  whoTitle: 'الأعمال التي<br/><em>نحقق لها النتائج.</em>',
  whoSub: 'نعمل مع الأعمال التي تقدّم خدمة قوية ولديها طموح حقيقي للنمو. هؤلاء من نعمل معهم عادةً في هذا القطاع.',
  mistakesLabel: 'أخطاء شائعة',
  mistakesTitle: '3 أخطاء<br/><em>تعيق نموّك.</em>',
  mistakesSub: 'قبل أن نبني أو نطلق أي شيء، نعالج المشكلات التي تقتل بصمت معظم المواقع والميزانيات الإعلانية.',
  systemLabel: 'نظام نموّك',
  systemTitle: 'الموقع والسيو والإعلانات،<br/><em>تعمل كمنظومة واحدة.</em>',
  system: (aud: string) => [
    { key: 'web', icon: 'monitor', t: 'موقع يكسب الثقة', d: `موقع سريع وفاخر مبني حول ما يحتاج ${aud} رؤيته قبل أن يتواصلوا.`, href: '/services/website-development' },
    { key: 'seo', icon: 'search', t: 'تصدّر حيث يبحثون', d: `سيو محلي وصفحات خدمات تضعك أمام ${aud} الذين يبحثون على جوجل الآن.`, href: '/services/seo' },
    { key: 'ads', icon: 'megaphone', t: 'عملاء هذا الشهر', d: `حملات ميتا وجوجل تجلب ${aud} المؤهَّلين بينما يتراكم ترتيبك في البحث.`, href: '/services/meta-ads' },
  ],
  expectLabel: 'ما الذي تتوقعه',
  expectTitle: 'عندما<br/><em>نعمل معاً.</em>',
  whyLabel: 'لماذا RizcoReach',
  why: [
    { k: '+5 ملايين', t: 'خبرة في السوق الإماراتي', d: 'استثمرنا أكثر من 5 ملايين درهم في الإعلانات المدفوعة في دبي والخليج. نعرف ما الذي يحقق التحويل في هذا السوق.' },
    { k: 'شهرياً', t: 'بلا عقود ملزمة', d: 'نعمل شهراً بشهر. نتائجنا هي ما يُبقيك معنا، لا العقد.' },
    { k: 'تخصّص', t: 'التخصّص في القطاعات', d: 'لا نعمل مع الجميع. هذا التركيز يعني نتائج أسرع وعملاً أدق لتخصصك.' },
  ],
  stepsLabel: 'الخطوات التالية',
  stepsTitle: 'كيف<br/><em>نعمل.</em>',
  steps: [
    { t: 'قدّم طلب استشارة', d: 'املأ نموذجاً قصيراً لنفهم عملك وأهدافك، وإن كنا الخيار المناسب لبعضنا.' },
    { t: 'مكالمة الاستراتيجية', d: 'نرسم بدقة كيف سنتعامل مع سوقك، وما سنبنيه، والنتائج التي يمكنك توقعها.' },
    { t: 'ننطلق', d: 'يُبنى موقعك وسيو وحملاتك ويُطلق ويُحسَّن. وتركّز أنت على العملاء.' },
  ],
  otherLabel: 'قطاعات أخرى',
  learn: 'اعرف المزيد',
};

export const industryUi = { en, ar };
