/** Copy for the free tools. {v} is replaced with the check's measured value. */

type CheckCopy = { name: string; pass: string; warn: string; fail: string; fix: string };

const checksEn: Record<string, CheckCopy> = {
  title: { name: 'Page title', pass: 'Title is {v} characters, a good length for Google.', warn: 'Title is {v} characters. Aim for 25–65 so it isn’t cut off or too thin.', fail: 'No page title found.', fix: 'Write a unique title with your main service and location, e.g. “Kitchen Fit-Out in Dubai | Brand”.' },
  description: { name: 'Meta description', pass: 'Meta description is {v} characters.', warn: 'Meta description is {v} characters. 70–165 works best in search results.', fail: 'No meta description found.', fix: 'Write a persuasive 1–2 sentence summary with a clear reason to click.' },
  h1: { name: 'Main heading (H1)', pass: 'Exactly one H1 heading.', warn: '{v} H1 headings found. Use one clear H1 per page.', fail: 'No H1 heading found.', fix: 'Add one H1 that states what you do and where, matching what customers search.' },
  headings: { name: 'Heading structure', pass: '{v} H2 subheadings structure the page.', warn: 'Only {v} H2 subheading.', fail: 'No H2 subheadings found.', fix: 'Break content into sections with descriptive H2s that include related keywords.' },
  canonical: { name: 'Canonical URL', pass: 'Canonical tag is set.', warn: 'No canonical tag.', fail: 'No canonical tag.', fix: 'Add a canonical link to tell Google which URL is the original.' },
  indexable: { name: 'Indexable by Google', pass: 'Page can be indexed.', warn: 'Indexing may be restricted.', fail: 'Page is set to “noindex”, so Google will not show it.', fix: 'Remove the noindex directive unless you intentionally hide this page.' },
  lang: { name: 'Language attribute', pass: 'Language is declared ({v}).', warn: 'No language declared on the page.', fail: 'No language declared.', fix: 'Add lang="en" (or "ar") to the <html> tag so search engines target the right audience.' },
  schema: { name: 'Structured data', pass: 'Structured data (schema) found.', warn: 'No structured data found.', fail: 'No structured data found.', fix: 'Add LocalBusiness / Organization schema so Google understands your business details.' },
  alt: { name: 'Image alt text', pass: 'Images have alt text ({v}).', warn: 'Some images are missing alt text ({v} have it).', fail: 'Most images are missing alt text ({v} have it).', fix: 'Describe every meaningful image. It helps accessibility and image search.' },
  content: { name: 'Content depth', pass: '{v} words of content.', warn: 'Only {v} words. Thin pages struggle to rank.', fail: 'Only {v} words. Google has very little to rank.', fix: 'Expand with genuinely useful copy: services, process, FAQs, areas served and proof.' },
  links: { name: 'Internal links', pass: '{v} internal links.', warn: 'Only {v} internal links.', fail: 'Almost no internal links ({v}).', fix: 'Link to your key service pages so visitors and Google can find them.' },
  robotsTxt: { name: 'robots.txt', pass: 'robots.txt found.', warn: 'No robots.txt found.', fail: 'No robots.txt found.', fix: 'Add a robots.txt file and reference your sitemap in it.' },
  sitemap: { name: 'XML sitemap', pass: 'XML sitemap found.', warn: 'No XML sitemap found.', fail: 'No XML sitemap found.', fix: 'Generate a sitemap.xml and submit it in Google Search Console.' },
  ttfb: { name: 'Server response time', pass: 'Server responded in {v} ms.', warn: 'Server took {v} ms to respond.', fail: 'Server took {v} ms to respond. That’s slow.', fix: 'Use faster hosting with a CDN and caching close to UAE visitors.' },
  htmlSize: { name: 'Page weight (HTML)', pass: 'HTML is {v} KB.', warn: 'HTML is {v} KB, heavier than ideal.', fail: 'HTML is {v} KB, very heavy.', fix: 'Remove bloated page-builder markup and inline code you don’t need.' },
  compression: { name: 'Compression', pass: 'Text is compressed ({v}).', warn: 'No gzip/brotli compression detected.', fail: 'No compression.', fix: 'Enable brotli or gzip compression on your server or CDN.' },
  renderBlocking: { name: 'Render-blocking scripts', pass: 'No render-blocking scripts in the head.', warn: '{v} scripts block the page from rendering.', fail: '{v} scripts block the page from rendering.', fix: 'Load scripts with defer/async, or remove the ones you don’t need.' },
  stylesheets: { name: 'Stylesheets', pass: '{v} stylesheets.', warn: '{v} separate stylesheets slow the first paint.', fail: '{v} separate stylesheets slow the first paint.', fix: 'Combine and trim CSS, and inline the critical styles.' },
  lazy: { name: 'Lazy-loaded images', pass: 'Images load efficiently ({v} lazy).', warn: 'Few images are lazy-loaded ({v}).', fail: 'No images are lazy-loaded ({v}).', fix: 'Add loading="lazy" to images below the fold.' },
  modernImages: { name: 'Modern image formats', pass: 'Modern image formats (WebP/AVIF) in use.', warn: 'No WebP or AVIF images detected.', fail: 'No modern image formats.', fix: 'Serve WebP/AVIF images. They’re often 30–50% smaller than JPG/PNG.' },
  viewport: { name: 'Mobile viewport', pass: 'Mobile viewport is configured.', warn: 'Mobile viewport is misconfigured.', fail: 'No mobile viewport tag, so the site won’t scale on phones.', fix: 'Add <meta name="viewport" content="width=device-width, initial-scale=1">.' },
  zoom: { name: 'Pinch-to-zoom', pass: 'Visitors can zoom.', warn: 'Zoom is disabled, which hurts accessibility.', fail: 'Zoom is disabled.', fix: 'Remove user-scalable=no / maximum-scale=1 from the viewport tag.' },
  contactLinks: { name: 'Tap-to-call / WhatsApp', pass: 'Click-to-contact links found ({v}).', warn: 'No tap-to-call or WhatsApp link.', fail: 'No tap-to-call or WhatsApp link, so mobile visitors can’t reach you in one tap.', fix: 'Add a tap-to-call and WhatsApp button, visible on every page.' },
  leadCapture: { name: 'Enquiry form', pass: 'An enquiry form is on the page.', warn: 'No form on this page, only an email link.', fail: 'No way to enquire on this page.', fix: 'Add a short enquiry form near the top and after key sections.' },
  favicon: { name: 'Favicon', pass: 'Favicon is set.', warn: 'No favicon found.', fail: 'No favicon found.', fix: 'Add a favicon so your brand shows in browser tabs and search results.' },
  https: { name: 'HTTPS', pass: 'Site is served securely over HTTPS.', warn: 'HTTPS issue.', fail: 'Site is not served over HTTPS. Browsers show “Not secure”.', fix: 'Install an SSL certificate and force HTTPS.' },
  hsts: { name: 'HSTS security header', pass: 'HSTS header is set.', warn: 'No HSTS header.', fail: 'No HSTS header.', fix: 'Add a Strict-Transport-Security header to enforce HTTPS.' },
  mixedContent: { name: 'Mixed content', pass: 'No insecure resources found.', warn: 'Some resources load over insecure http://.', fail: 'Insecure resources found.', fix: 'Load every image, script and stylesheet over https://.' },
  social: { name: 'Social sharing preview', pass: 'Open Graph tags are set.', warn: 'Missing Open Graph title or image, so links shared on WhatsApp look bare.', fail: 'No Open Graph tags.', fix: 'Add og:title, og:description and og:image tags.' },
  httpRedirect: { name: 'HTTP → HTTPS redirect', pass: 'http:// redirects to https://.', warn: 'http:// does not redirect to https://.', fail: 'No HTTPS redirect.', fix: 'Redirect all http:// traffic to https:// with a 301.' },
};

const checksAr: Record<string, CheckCopy> = {
  title: { name: 'عنوان الصفحة', pass: 'العنوان {v} حرفاً، طول مناسب لجوجل.', warn: 'العنوان {v} حرفاً. الأفضل بين 25 و65 حرفاً.', fail: 'لا يوجد عنوان للصفحة.', fix: 'اكتب عنواناً فريداً يتضمن خدمتك الرئيسية والمنطقة، مثل "تشطيب مطابخ في دبي | اسم العلامة".' },
  description: { name: 'الوصف التعريفي', pass: 'الوصف التعريفي {v} حرفاً.', warn: 'الوصف التعريفي {v} حرفاً. الأفضل بين 70 و165 حرفاً.', fail: 'لا يوجد وصف تعريفي.', fix: 'اكتب ملخصاً مقنعاً من جملة أو جملتين مع سبب واضح للنقر.' },
  h1: { name: 'العنوان الرئيسي (H1)', pass: 'عنوان H1 واحد بالضبط.', warn: 'يوجد {v} عناوين H1. استخدم عنواناً واحداً واضحاً.', fail: 'لا يوجد عنوان H1.', fix: 'أضف عنوان H1 واحداً يوضّح ما تقدّمه وأين، بما يطابق بحث العملاء.' },
  headings: { name: 'هيكل العناوين', pass: '{v} عناوين فرعية H2 تنظّم الصفحة.', warn: 'عنوان فرعي H2 واحد فقط.', fail: 'لا توجد عناوين فرعية H2.', fix: 'قسّم المحتوى إلى أقسام بعناوين H2 وصفية تتضمن كلمات ذات صلة.' },
  canonical: { name: 'الرابط الأساسي (Canonical)', pass: 'وسم Canonical موجود.', warn: 'لا يوجد وسم Canonical.', fail: 'لا يوجد وسم Canonical.', fix: 'أضف رابطاً أساسياً ليعرف جوجل الرابط الأصلي للصفحة.' },
  indexable: { name: 'قابلية الفهرسة', pass: 'يمكن لجوجل فهرسة الصفحة.', warn: 'قد تكون الفهرسة مقيّدة.', fail: 'الصفحة مضبوطة على "noindex" ولن تظهر في جوجل.', fix: 'أزل توجيه noindex إلا إن كنت تخفي الصفحة عمداً.' },
  lang: { name: 'سمة اللغة', pass: 'تم تحديد اللغة ({v}).', warn: 'لم يتم تحديد لغة الصفحة.', fail: 'لم يتم تحديد اللغة.', fix: 'أضف lang="ar" أو lang="en" إلى وسم <html> لاستهداف الجمهور الصحيح.' },
  schema: { name: 'البيانات المنظّمة', pass: 'توجد بيانات منظّمة (سكيما).', warn: 'لا توجد بيانات منظّمة.', fail: 'لا توجد بيانات منظّمة.', fix: 'أضف سكيما LocalBusiness أو Organization ليفهم جوجل تفاصيل عملك.' },
  alt: { name: 'النص البديل للصور', pass: 'الصور تحتوي نصاً بديلاً ({v}).', warn: 'بعض الصور بلا نص بديل ({v} لديها).', fail: 'معظم الصور بلا نص بديل ({v} لديها).', fix: 'صِف كل صورة مهمة، فذلك يدعم إمكانية الوصول والبحث بالصور.' },
  content: { name: 'عمق المحتوى', pass: '{v} كلمة من المحتوى.', warn: '{v} كلمة فقط. الصفحات الضعيفة يصعب تصدّرها.', fail: '{v} كلمة فقط. لا يجد جوجل ما يرتّبه.', fix: 'أضف محتوى مفيداً: الخدمات والمنهجية والأسئلة الشائعة والمناطق والأدلة.' },
  links: { name: 'الروابط الداخلية', pass: '{v} رابطاً داخلياً.', warn: '{v} روابط داخلية فقط.', fail: 'روابط داخلية شبه معدومة ({v}).', fix: 'اربط صفحات خدماتك الرئيسية ليجدها الزوار وجوجل.' },
  robotsTxt: { name: 'ملف robots.txt', pass: 'ملف robots.txt موجود.', warn: 'لا يوجد ملف robots.txt.', fail: 'لا يوجد ملف robots.txt.', fix: 'أضف ملف robots.txt واذكر فيه خريطة الموقع.' },
  sitemap: { name: 'خريطة الموقع XML', pass: 'خريطة الموقع موجودة.', warn: 'لا توجد خريطة موقع XML.', fail: 'لا توجد خريطة موقع XML.', fix: 'أنشئ ملف sitemap.xml وقدّمه في Google Search Console.' },
  ttfb: { name: 'زمن استجابة الخادم', pass: 'استجاب الخادم خلال {v} ملّي ثانية.', warn: 'استغرق الخادم {v} ملّي ثانية للاستجابة.', fail: 'استغرق الخادم {v} ملّي ثانية. هذا بطيء.', fix: 'استخدم استضافة أسرع مع شبكة CDN وتخزين مؤقت قريب من زوار الإمارات.' },
  htmlSize: { name: 'حجم الصفحة (HTML)', pass: 'حجم HTML ‏{v} كيلوبايت.', warn: 'حجم HTML ‏{v} كيلوبايت، أثقل من المثالي.', fail: 'حجم HTML ‏{v} كيلوبايت، ثقيل جداً.', fix: 'أزل الأكواد الزائدة من منشئي الصفحات والأكواد المضمّنة غير الضرورية.' },
  compression: { name: 'الضغط', pass: 'النصوص مضغوطة ({v}).', warn: 'لم يُكتشف ضغط gzip أو brotli.', fail: 'لا يوجد ضغط.', fix: 'فعّل ضغط brotli أو gzip على الخادم أو CDN.' },
  renderBlocking: { name: 'سكربتات تعيق العرض', pass: 'لا توجد سكربتات تعيق عرض الصفحة.', warn: '{v} سكربتات تعيق عرض الصفحة.', fail: '{v} سكربتات تعيق عرض الصفحة.', fix: 'حمّل السكربتات بخاصية defer أو async، أو أزل غير الضروري منها.' },
  stylesheets: { name: 'ملفات التنسيق', pass: '{v} ملفات تنسيق.', warn: '{v} ملفات تنسيق منفصلة تبطئ العرض الأول.', fail: '{v} ملفات تنسيق منفصلة تبطئ العرض الأول.', fix: 'ادمج ملفات CSS وقلّصها، وضمّن التنسيقات الحرجة.' },
  lazy: { name: 'التحميل الكسول للصور', pass: 'الصور تُحمَّل بكفاءة ({v} كسول).', warn: 'قلة من الصور تُحمَّل بكسل ({v}).', fail: 'لا توجد صور بتحميل كسول ({v}).', fix: 'أضف loading="lazy" للصور أسفل الشاشة الأولى.' },
  modernImages: { name: 'صيغ الصور الحديثة', pass: 'تُستخدم صيغ حديثة (WebP/AVIF).', warn: 'لم تُكتشف صور WebP أو AVIF.', fail: 'لا توجد صيغ صور حديثة.', fix: 'استخدم صور WebP/AVIF، فهي غالباً أصغر بنسبة 30–50% من JPG/PNG.' },
  viewport: { name: 'إطار العرض للجوال', pass: 'إطار العرض للجوال مضبوط.', warn: 'إطار العرض للجوال غير مضبوط.', fail: 'لا يوجد وسم viewport، فلن يتكيّف الموقع مع الجوال.', fix: 'أضف <meta name="viewport" content="width=device-width, initial-scale=1">.' },
  zoom: { name: 'التكبير باللمس', pass: 'يمكن للزوار التكبير.', warn: 'التكبير معطّل، ما يضر بإمكانية الوصول.', fail: 'التكبير معطّل.', fix: 'أزل user-scalable=no و maximum-scale=1 من وسم viewport.' },
  contactLinks: { name: 'الاتصال وواتساب بلمسة', pass: 'توجد روابط تواصل مباشر ({v}).', warn: 'لا يوجد رابط اتصال أو واتساب.', fail: 'لا يوجد رابط اتصال أو واتساب، فلا يستطيع زوار الجوال التواصل بلمسة.', fix: 'أضف زر اتصال وزر واتساب ظاهرين في كل صفحة.' },
  leadCapture: { name: 'نموذج الطلب', pass: 'يوجد نموذج طلب في الصفحة.', warn: 'لا يوجد نموذج، فقط رابط بريد إلكتروني.', fail: 'لا توجد طريقة لتقديم طلب في هذه الصفحة.', fix: 'أضف نموذج طلب قصيراً في الأعلى وبعد الأقسام الرئيسية.' },
  favicon: { name: 'أيقونة الموقع', pass: 'أيقونة الموقع موجودة.', warn: 'لا توجد أيقونة للموقع.', fail: 'لا توجد أيقونة للموقع.', fix: 'أضف أيقونة لتظهر علامتك في تبويبات المتصفح ونتائج البحث.' },
  https: { name: 'HTTPS', pass: 'الموقع يعمل بأمان عبر HTTPS.', warn: 'مشكلة في HTTPS.', fail: 'الموقع لا يعمل عبر HTTPS، وتعرض المتصفحات "غير آمن".', fix: 'ثبّت شهادة SSL وافرض HTTPS.' },
  hsts: { name: 'ترويسة أمان HSTS', pass: 'ترويسة HSTS موجودة.', warn: 'لا توجد ترويسة HSTS.', fail: 'لا توجد ترويسة HSTS.', fix: 'أضف ترويسة Strict-Transport-Security لفرض HTTPS.' },
  mixedContent: { name: 'المحتوى المختلط', pass: 'لا توجد موارد غير آمنة.', warn: 'بعض الموارد تُحمَّل عبر http:// غير الآمن.', fail: 'توجد موارد غير آمنة.', fix: 'حمّل جميع الصور والسكربتات والتنسيقات عبر https://.' },
  social: { name: 'معاينة المشاركة', pass: 'وسوم Open Graph موجودة.', warn: 'ينقص عنوان أو صورة Open Graph، فتظهر الروابط المشتركة على واتساب فارغة.', fail: 'لا توجد وسوم Open Graph.', fix: 'أضف وسوم og:title و og:description و og:image.' },
  httpRedirect: { name: 'التحويل من HTTP إلى HTTPS', pass: 'رابط http:// يتحوّل إلى https://.', warn: 'رابط http:// لا يتحوّل إلى https://.', fail: 'لا يوجد تحويل إلى HTTPS.', fix: 'حوّل كل زيارات http:// إلى https:// بتحويل 301.' },
};

const en = {
  hub: {
    metaTitle: 'Free Growth Tools: Website Audit, SEO & Ads Calculators | RizcoReach',
    metaDescription: 'Free tools for UAE businesses: instant website audit, SEO revenue calculator, Meta Ads calculator and website project estimator.',
    kicker: 'Free growth tools',
    title: 'Tools that are useful <em>before you even call us.</em>',
    sub: 'The same tools we use to scope projects, free for you. No sign-up needed to start.',
  },
  gate: {
    title: 'Unlock your full report',
    sub: 'Enter your details to see the complete breakdown. A strategist will also review it and send you a prioritised plan within 24 hours.',
    name: 'Your name',
    email: 'Email',
    phone: 'WhatsApp (optional)',
    submit: 'Unlock full report',
    sending: 'Unlocking…',
    privacy: 'No spam. We only use your details to send your report and follow up on it.',
    error: 'Please enter your name and a valid email.',
    sendError: 'We couldn’t send that just now. Please try again.',
    unlocked: 'Unlocked. A strategist will be in touch within 24 hours.',
    locked: 'Locked',
  },
  audit: {
    metaTitle: 'Free Website Audit Tool: SEO, Speed & Mobile Check | RizcoReach',
    metaDescription: 'Run a free instant website audit. Check your SEO, speed, mobile experience and trust signals, and get a clear list of fixes.',
    kicker: 'Free tool · Website audit',
    title: 'How good is your website, <em>really?</em>',
    sub: 'Enter any URL. In about 10 seconds we check 30 SEO, speed, mobile and trust signals, and show you exactly what to fix.',
    placeholder: 'yourwebsite.ae',
    run: 'Run free audit',
    label: 'Website address',
    invalid: 'Please enter a valid website address, like yourbusiness.ae',
    steps: ['Fetching your page', 'Checking SEO signals', 'Measuring speed', 'Testing mobile & conversion', 'Checking security & trust'],
    errors: {
      invalid_url: 'That address doesn’t look right. Try something like yourbusiness.ae',
      unreachable: 'We couldn’t reach that website. Check the address and try again.',
      http_error: 'That page returned an error ({v}). Try your homepage URL.',
      not_html: 'That address isn’t a web page. Try your homepage URL.',
      generic: 'Something went wrong running the audit. Please try again.',
    },
    overall: 'Overall score',
    grade: { great: 'Strong foundation', ok: 'Room to grow', poor: 'Needs urgent attention' },
    gradeSub: {
      great: 'Your site gets the basics right. The next gains come from content, speed and conversion polish.',
      ok: 'Solid in places, but several issues are costing you rankings and enquiries.',
      poor: 'Key issues are holding this site back from Google and from converting visitors.',
    },
    cats: { seo: 'SEO', speed: 'Speed', mobile: 'Mobile & conversion', trust: 'Trust & security' },
    passed: 'passed',
    topIssues: 'Top issues to fix',
    noIssues: 'No major issues found. Nice work.',
    fullReport: 'Full report',
    checksLabel: 'checks',
    lighthouse: 'Google Lighthouse (mobile)',
    lighthouseLoading: 'Running Google Lighthouse… this can take up to 30 seconds.',
    lighthouseNA: 'Lighthouse scores are unavailable right now. They’ll be included in your strategist’s review.',
    lh: { performance: 'Performance', accessibility: 'Accessibility', bestPractices: 'Best practices', seo: 'SEO' },
    vitals: { lcp: 'Largest contentful paint', cls: 'Layout shift', tbt: 'Blocking time' },
    status: { pass: 'Pass', warn: 'Improve', fail: 'Fix' },
    howTo: 'How to fix',
    again: 'Audit another site',
    print: 'Save as PDF',
    analysed: 'Analysed',
    cta: 'Want us to fix all of this?',
    ctaSub: 'We build fast, SEO-ready websites that pass every one of these checks.',
    ctaBtn: 'Get a free strategy call',
    disclaimer: 'This audit analyses the page’s HTML and response headers. It’s an indicative check, not a full technical crawl.',
    checks: checksEn,
  },
  seo: {
    metaTitle: 'SEO Revenue Calculator: What Is Page One Worth? | RizcoReach',
    metaDescription: 'Estimate the extra traffic, leads and revenue better Google rankings could bring your business. Free SEO ROI calculator for UAE businesses.',
    kicker: 'Free tool · SEO revenue calculator',
    title: 'What is page one <em>worth to you?</em>',
    sub: 'Model the extra visitors, enquiries and revenue that better Google rankings could bring your business.',
    inputs: 'Your numbers',
    searches: 'Monthly searches for your main services',
    searchesHint: 'Total Google searches per month for the services you sell, in the areas you serve.',
    current: 'Where you rank today',
    target: 'Where you want to rank',
    positions: { none: 'Not ranking', p2: 'Page 2', p4: 'Positions 4–10', top3: 'Top 3', p1: '#1' },
    conv: 'Website enquiry rate',
    convHint: 'Share of visitors who enquire. 2–5% is typical for service businesses.',
    close: 'Enquiry-to-customer rate',
    value: 'Average customer value (AED)',
    resultLabel: 'Ranking higher could be worth',
    perMonth: 'per month in new revenue',
    tiles: { visitors: 'Extra visitors / month', leads: 'Extra enquiries / month', customers: 'New customers / month', year: 'Revenue at full ranking / year' },
    chartTitle: 'Projected extra monthly revenue, first 12 months',
    chartSub: 'SEO compounds: rankings build over time, so revenue ramps up month by month.',
    month: 'Month',
    year1: 'Estimated first-year revenue',
    year2: 'Run-rate from year two',
    assumptions: 'Click-through rates are industry averages by Google position. Real results depend on competition, content and your website’s ability to convert.',
    noUplift: 'Choose a target position above your current one to see the uplift.',
  },
  ads: {
    metaTitle: 'Meta Ads Calculator: Leads, Cost per Lead & ROAS | RizcoReach',
    metaDescription: 'Forecast leads, cost per lead, customers and ROAS from your Meta (Facebook & Instagram) ad budget, using indicative UAE benchmarks by industry.',
    kicker: 'Free tool · Meta Ads calculator',
    title: 'Forecast your <em>Meta Ads</em> results.',
    sub: 'Enter your budget and customer value to estimate leads, cost per lead, customers and return on ad spend.',
    inputs: 'Your campaign',
    industry: 'Your industry',
    budget: 'Monthly ad budget (AED)',
    close: 'Lead-to-customer rate',
    value: 'Average customer value (AED)',
    cplLabel: 'Cost per lead (AED)',
    cplHint: 'Pre-filled with an indicative UAE range for your industry. Adjust it if you know your numbers.',
    resultLabel: 'Estimated leads per month',
    tiles: { cpl: 'Est. cost per lead', customers: 'New customers / month', revenue: 'Revenue / month', roas: 'Return on ad spend' },
    roasNote: 'ROAS = revenue ÷ ad spend',
    scenariosTitle: 'Budget scenarios',
    scenariosSub: 'Same assumptions at different monthly budgets. Real CPL usually rises a little as you scale.',
    scenarioCols: ['Budget', 'Leads', 'Customers', 'Revenue', 'ROAS'],
    breakeven: 'Break-even close rate',
    breakevenSub: 'The share of leads you need to close for the ads to pay for themselves.',
    costPerCustomer: 'Cost per customer',
    tipsTitle: 'What lowers your cost per lead',
    tips: ['A specific, compelling offer, not a generic “contact us”', 'Fresh creative every week to beat ad fatigue', 'Instant lead forms that pre-qualify on budget and location', 'Fast follow-up: replying within 5 minutes lifts conversion dramatically'],
    disclaimer: 'Benchmarks are indicative ranges for UAE lead-generation campaigns. Actual results depend on your offer, creative, targeting and follow-up.',
    industries: [
      { k: 'home', t: 'Construction & home improvement', cpl: [30, 90] },
      { k: 'land', t: 'Landscaping', cpl: [25, 75] },
      { k: 'health', t: 'Healthcare & clinics', cpl: [40, 120] },
      { k: 'aes', t: 'Aesthetics & beauty', cpl: [25, 80] },
      { k: 'fit', t: 'Fitness & pilates', cpl: [20, 60] },
      { k: 'corp', t: 'Corporate services', cpl: [60, 180] },
      { k: 'it', t: 'IT & software', cpl: [80, 250] },
      { k: 'pro', t: 'Professional & B2B', cpl: [60, 200] },
      { k: 'other', t: 'Other', cpl: [40, 120] },
    ],
  },
  est: {
    metaTitle: 'Website Project Estimator: Scope & Timeline | RizcoReach',
    metaDescription: 'Plan your new website in two minutes. Choose pages and features to see your project scope and typical timeline, then get a tailored quote.',
    kicker: 'Free tool · Website project estimator',
    title: 'Plan your website <em>in two minutes.</em>',
    sub: 'Choose your pages and features to see the scope, complexity and typical timeline of your project. Then get a tailored quote from our team.',
    type: 'What are you building?',
    types: [
      { k: 'landing', t: 'Landing page', d: 'One focused page for a campaign or offer' },
      { k: 'business', t: 'Business website', d: 'Services, about, contact and more' },
      { k: 'ecommerce', t: 'E-commerce store', d: 'Products, cart and online payments' },
      { k: 'webapp', t: 'Custom web app', d: 'Portals, dashboards, bespoke features' },
    ],
    pages: 'How many pages?',
    pagesUnit: 'pages',
    features: 'Features you need',
    featureList: [
      { k: 'bilingual', t: 'English & Arabic' },
      { k: 'booking', t: 'Booking / appointments' },
      { k: 'cms', t: 'Blog / editable content' },
      { k: 'shop', t: 'Online payments' },
      { k: 'integrations', t: 'CRM & integrations' },
      { k: 'motion', t: 'Premium animations / 3D' },
      { k: 'copy', t: 'Copywriting' },
      { k: 'branding', t: 'Logo & brand identity' },
      { k: 'portal', t: 'Client login / portal' },
    ],
    design: 'Design level',
    designs: [
      { k: 'clean', t: 'Clean & professional' },
      { k: 'premium', t: 'Premium custom' },
      { k: 'flagship', t: 'Flagship, award-level' },
    ],
    timing: 'When do you need it?',
    timings: [
      { k: 'flexible', t: 'Flexible' },
      { k: 'standard', t: 'In the next 1–2 months' },
      { k: 'urgent', t: 'As soon as possible' },
    ],
    summary: 'Your project',
    tier: 'Project tier',
    tiers: { launch: 'Launch', growth: 'Growth', flagship: 'Flagship', custom: 'Custom build' },
    timeline: 'Typical timeline',
    weeks: 'weeks',
    complexity: 'Complexity',
    includes: 'Always included',
    included: ['Mobile-first, custom design', 'SEO foundations & schema', 'Speed optimisation', 'WhatsApp, call & enquiry CTAs', 'Analytics & Search Console setup'],
    yourScope: 'Your scope',
    quoteTitle: 'Get your exact quote',
    quoteSub: 'We’ll review your scope and send a clear, itemised quote within 24 hours. No obligation.',
    quoteBtn: 'Request my quote',
    sent: 'Quote request received. We’ll be in touch within 24 hours.',
    note: 'Timelines are typical ranges once content is ready. Your quote confirms exact scope and dates.',
  },
};

const ar: typeof en = {
  hub: {
    metaTitle: 'أدوات نموّ مجانية: فحص المواقع وحاسبات السيو والإعلانات | RizcoReach',
    metaDescription: 'أدوات مجانية للشركات في الإمارات: فحص فوري للمواقع، وحاسبة عائد السيو، وحاسبة إعلانات ميتا، ومُخطِّط مشروع الموقع.',
    kicker: 'أدوات نموّ مجانية',
    title: 'أدوات مفيدة <em>حتى قبل أن تتصل بنا.</em>',
    sub: 'الأدوات نفسها التي نستخدمها لتقدير المشاريع، مجاناً لك. لا حاجة للتسجيل للبدء.',
  },
  gate: {
    title: 'افتح تقريرك الكامل',
    sub: 'أدخل بياناتك لرؤية التحليل الكامل. وسيراجعه أحد خبرائنا ويرسل لك خطة بالأولويات خلال 24 ساعة.',
    name: 'اسمك',
    email: 'البريد الإلكتروني',
    phone: 'واتساب (اختياري)',
    submit: 'افتح التقرير الكامل',
    sending: 'جارٍ الفتح…',
    privacy: 'بلا رسائل مزعجة. نستخدم بياناتك فقط لإرسال تقريرك ومتابعته.',
    error: 'يرجى إدخال اسمك وبريد إلكتروني صحيح.',
    sendError: 'تعذّر الإرسال الآن. يرجى المحاولة مجدداً.',
    unlocked: 'تم الفتح. سيتواصل معك أحد خبرائنا خلال 24 ساعة.',
    locked: 'مقفل',
  },
  audit: {
    metaTitle: 'أداة فحص المواقع المجانية: السيو والسرعة والجوال | RizcoReach',
    metaDescription: 'افحص موقعك مجاناً وفوراً. تحقّق من السيو والسرعة وتجربة الجوال وعوامل الثقة، واحصل على قائمة واضحة بالإصلاحات.',
    kicker: 'أداة مجانية · فحص الموقع',
    title: 'ما مدى جودة موقعك <em>فعلاً؟</em>',
    sub: 'أدخل أي رابط. خلال نحو 10 ثوانٍ نفحص 30 عاملاً في السيو والسرعة والجوال والثقة، ونريك بالضبط ما يجب إصلاحه.',
    placeholder: 'yourwebsite.ae',
    run: 'ابدأ الفحص المجاني',
    label: 'عنوان الموقع',
    invalid: 'يرجى إدخال عنوان موقع صحيح، مثل yourbusiness.ae',
    steps: ['جلب صفحتك', 'فحص عوامل السيو', 'قياس السرعة', 'اختبار الجوال والتحويل', 'فحص الأمان والثقة'],
    errors: {
      invalid_url: 'العنوان لا يبدو صحيحاً. جرّب مثل yourbusiness.ae',
      unreachable: 'تعذّر الوصول إلى الموقع. تحقّق من العنوان وحاول مجدداً.',
      http_error: 'أعادت الصفحة خطأ ({v}). جرّب رابط الصفحة الرئيسية.',
      not_html: 'هذا العنوان ليس صفحة ويب. جرّب رابط الصفحة الرئيسية.',
      generic: 'حدث خطأ أثناء الفحص. يرجى المحاولة مجدداً.',
    },
    overall: 'التقييم العام',
    grade: { great: 'أساس قوي', ok: 'مجال للتحسين', poor: 'يحتاج اهتماماً عاجلاً' },
    gradeSub: {
      great: 'موقعك يتقن الأساسيات. المكاسب التالية من المحتوى والسرعة وتحسين التحويل.',
      ok: 'جيد في جوانب، لكن عدة مشكلات تكلّفك ترتيباً وطلبات.',
      poor: 'مشكلات رئيسية تمنع هذا الموقع من الظهور في جوجل وتحويل الزوار.',
    },
    cats: { seo: 'السيو', speed: 'السرعة', mobile: 'الجوال والتحويل', trust: 'الثقة والأمان' },
    passed: 'ناجح',
    topIssues: 'أهم المشكلات للإصلاح',
    noIssues: 'لا توجد مشكلات رئيسية. عمل رائع.',
    fullReport: 'التقرير الكامل',
    checksLabel: 'فحصاً',
    lighthouse: 'جوجل لايتهاوس (الجوال)',
    lighthouseLoading: 'جارٍ تشغيل جوجل لايتهاوس… قد يستغرق حتى 30 ثانية.',
    lighthouseNA: 'نتائج لايتهاوس غير متاحة الآن، وستُضمَّن في مراجعة الخبير.',
    lh: { performance: 'الأداء', accessibility: 'إمكانية الوصول', bestPractices: 'أفضل الممارسات', seo: 'السيو' },
    vitals: { lcp: 'أكبر عرض للمحتوى', cls: 'إزاحة التخطيط', tbt: 'زمن الحجب' },
    status: { pass: 'ناجح', warn: 'حسّن', fail: 'أصلح' },
    howTo: 'كيفية الإصلاح',
    again: 'افحص موقعاً آخر',
    print: 'احفظ كملف PDF',
    analysed: 'تم تحليل',
    cta: 'تريدنا أن نصلح كل هذا؟',
    ctaSub: 'نبني مواقع سريعة وجاهزة للسيو تجتاز كل هذه الفحوصات.',
    ctaBtn: 'احصل على استشارة مجانية',
    disclaimer: 'يحلّل هذا الفحص كود HTML للصفحة وترويسات الاستجابة. إنه فحص تقديري، لا زحف تقني كامل.',
    checks: checksAr,
  },
  seo: {
    metaTitle: 'حاسبة عائد السيو: كم تساوي الصفحة الأولى؟ | RizcoReach',
    metaDescription: 'قدّر الزيارات والعملاء والإيرادات الإضافية التي قد يجلبها ترتيب أفضل في جوجل لعملك. حاسبة مجانية للشركات في الإمارات.',
    kicker: 'أداة مجانية · حاسبة عائد السيو',
    title: 'كم تساوي الصفحة الأولى <em>بالنسبة لك؟</em>',
    sub: 'احسب الزيارات والطلبات والإيرادات الإضافية التي قد يجلبها ترتيب أفضل في جوجل لعملك.',
    inputs: 'أرقامك',
    searches: 'عمليات البحث الشهرية عن خدماتك الرئيسية',
    searchesHint: 'إجمالي عمليات البحث الشهرية في جوجل عن الخدمات التي تبيعها في المناطق التي تخدمها.',
    current: 'ترتيبك اليوم',
    target: 'الترتيب المستهدف',
    positions: { none: 'غير ظاهر', p2: 'الصفحة 2', p4: 'المراكز 4–10', top3: 'أول 3 نتائج', p1: 'المركز الأول' },
    conv: 'نسبة الطلبات من الموقع',
    convHint: 'نسبة الزوار الذين يقدّمون طلباً. 2–5% معتاد لشركات الخدمات.',
    close: 'نسبة تحويل الطلب إلى عميل',
    value: 'متوسط قيمة العميل (درهم)',
    resultLabel: 'قد يساوي الترتيب الأعلى',
    perMonth: 'شهرياً من الإيرادات الجديدة',
    tiles: { visitors: 'زوار إضافيون / شهر', leads: 'طلبات إضافية / شهر', customers: 'عملاء جدد / شهر', year: 'الإيرادات عند الترتيب الكامل / سنة' },
    chartTitle: 'الإيرادات الشهرية الإضافية المتوقعة، أول 12 شهراً',
    chartSub: 'السيو يتراكم: يُبنى الترتيب مع الوقت، فترتفع الإيرادات شهراً بعد شهر.',
    month: 'الشهر',
    year1: 'الإيرادات المقدّرة للسنة الأولى',
    year2: 'المعدل السنوي من السنة الثانية',
    assumptions: 'نسب النقر هي متوسطات القطاع حسب الترتيب في جوجل. تعتمد النتائج الفعلية على المنافسة والمحتوى وقدرة موقعك على التحويل.',
    noUplift: 'اختر ترتيباً مستهدفاً أعلى من ترتيبك الحالي لرؤية الزيادة.',
  },
  ads: {
    metaTitle: 'حاسبة إعلانات ميتا: العملاء وتكلفة العميل والعائد | RizcoReach',
    metaDescription: 'توقّع عدد العملاء وتكلفة العميل والعائد على الإنفاق من ميزانية إعلانات ميتا (فيسبوك وإنستغرام)، بمعايير تقديرية للإمارات حسب القطاع.',
    kicker: 'أداة مجانية · حاسبة إعلانات ميتا',
    title: 'توقّع نتائج <em>إعلانات ميتا.</em>',
    sub: 'أدخل ميزانيتك وقيمة العميل لتقدير عدد العملاء وتكلفة العميل والعملاء الفعليين والعائد على الإنفاق الإعلاني.',
    inputs: 'حملتك',
    industry: 'قطاعك',
    budget: 'الميزانية الإعلانية الشهرية (درهم)',
    close: 'نسبة تحويل العميل المحتمل إلى عميل',
    value: 'متوسط قيمة العميل (درهم)',
    cplLabel: 'تكلفة العميل المحتمل (درهم)',
    cplHint: 'مُعبّأة بنطاق تقديري للإمارات حسب قطاعك. عدّلها إن كنت تعرف أرقامك.',
    resultLabel: 'عدد العملاء المحتملين شهرياً',
    tiles: { cpl: 'تكلفة العميل المقدّرة', customers: 'عملاء جدد / شهر', revenue: 'الإيرادات / شهر', roas: 'العائد على الإنفاق' },
    roasNote: 'العائد = الإيرادات ÷ الإنفاق الإعلاني',
    scenariosTitle: 'سيناريوهات الميزانية',
    scenariosSub: 'الافتراضات نفسها بميزانيات شهرية مختلفة. عادةً ترتفع تكلفة العميل قليلاً مع التوسّع.',
    scenarioCols: ['الميزانية', 'العملاء المحتملون', 'العملاء', 'الإيرادات', 'العائد'],
    breakeven: 'نسبة الإغلاق للتعادل',
    breakevenSub: 'نسبة العملاء المحتملين التي تحتاج إغلاقها لتغطي الإعلانات تكلفتها.',
    costPerCustomer: 'تكلفة العميل الفعلي',
    tipsTitle: 'ما الذي يخفّض تكلفة العميل',
    tips: ['عرض محدد ومقنع، لا مجرد "تواصل معنا"', 'تصاميم جديدة كل أسبوع لتجنّب ملل الجمهور', 'نماذج فورية تؤهّل حسب الميزانية والموقع', 'متابعة سريعة: الرد خلال 5 دقائق يرفع التحويل بشكل كبير'],
    disclaimer: 'المعايير نطاقات تقديرية لحملات استقطاب العملاء في الإمارات. تعتمد النتائج الفعلية على عرضك وتصاميمك واستهدافك ومتابعتك.',
    industries: [
      { k: 'home', t: 'المقاولات وتحسين المنازل', cpl: [30, 90] },
      { k: 'land', t: 'تنسيق الحدائق', cpl: [25, 75] },
      { k: 'health', t: 'الرعاية الصحية والعيادات', cpl: [40, 120] },
      { k: 'aes', t: 'التجميل والعناية', cpl: [25, 80] },
      { k: 'fit', t: 'اللياقة والبيلاتس', cpl: [20, 60] },
      { k: 'corp', t: 'خدمات الشركات', cpl: [60, 180] },
      { k: 'it', t: 'تقنية المعلومات والبرمجيات', cpl: [80, 250] },
      { k: 'pro', t: 'الخدمات المهنية', cpl: [60, 200] },
      { k: 'other', t: 'أخرى', cpl: [40, 120] },
    ],
  },
  est: {
    metaTitle: 'مُخطِّط مشروع الموقع: النطاق والجدول الزمني | RizcoReach',
    metaDescription: 'خطّط موقعك الجديد في دقيقتين. اختر الصفحات والميزات لترى نطاق مشروعك وجدوله الزمني المعتاد، ثم احصل على عرض سعر مخصّص.',
    kicker: 'أداة مجانية · مُخطِّط مشروع الموقع',
    title: 'خطّط موقعك <em>في دقيقتين.</em>',
    sub: 'اختر صفحاتك وميزاتك لترى نطاق مشروعك ومدى تعقيده وجدوله الزمني المعتاد، ثم احصل على عرض سعر مخصّص من فريقنا.',
    type: 'ماذا تبني؟',
    types: [
      { k: 'landing', t: 'صفحة هبوط', d: 'صفحة واحدة مركّزة لحملة أو عرض' },
      { k: 'business', t: 'موقع أعمال', d: 'الخدمات ومن نحن والتواصل وغيرها' },
      { k: 'ecommerce', t: 'متجر إلكتروني', d: 'منتجات وسلة ودفع إلكتروني' },
      { k: 'webapp', t: 'تطبيق ويب مخصّص', d: 'بوابات ولوحات تحكّم وميزات خاصة' },
    ],
    pages: 'كم عدد الصفحات؟',
    pagesUnit: 'صفحة',
    features: 'الميزات التي تحتاجها',
    featureList: [
      { k: 'bilingual', t: 'العربية والإنجليزية' },
      { k: 'booking', t: 'الحجوزات والمواعيد' },
      { k: 'cms', t: 'مدوّنة / محتوى قابل للتعديل' },
      { k: 'shop', t: 'الدفع الإلكتروني' },
      { k: 'integrations', t: 'CRM والتكاملات' },
      { k: 'motion', t: 'حركات فاخرة / ثلاثي الأبعاد' },
      { k: 'copy', t: 'كتابة المحتوى' },
      { k: 'branding', t: 'الشعار والهوية' },
      { k: 'portal', t: 'تسجيل دخول للعملاء' },
    ],
    design: 'مستوى التصميم',
    designs: [
      { k: 'clean', t: 'نظيف واحترافي' },
      { k: 'premium', t: 'مخصّص وفاخر' },
      { k: 'flagship', t: 'رائد بمستوى الجوائز' },
    ],
    timing: 'متى تحتاجه؟',
    timings: [
      { k: 'flexible', t: 'مرن' },
      { k: 'standard', t: 'خلال شهر إلى شهرين' },
      { k: 'urgent', t: 'في أقرب وقت' },
    ],
    summary: 'مشروعك',
    tier: 'فئة المشروع',
    tiers: { launch: 'انطلاق', growth: 'نموّ', flagship: 'رائد', custom: 'بناء مخصّص' },
    timeline: 'الجدول الزمني المعتاد',
    weeks: 'أسابيع',
    complexity: 'مستوى التعقيد',
    includes: 'مشمول دائماً',
    included: ['تصميم مخصّص للجوال أولاً', 'أسس السيو والسكيما', 'تحسين السرعة', 'أزرار واتساب واتصال وطلب', 'إعداد التحليلات وSearch Console'],
    yourScope: 'نطاق مشروعك',
    quoteTitle: 'احصل على عرض سعرك الدقيق',
    quoteSub: 'سنراجع نطاق مشروعك ونرسل عرض سعر واضحاً ومفصّلاً خلال 24 ساعة، دون أي التزام.',
    quoteBtn: 'اطلب عرض السعر',
    sent: 'تم استلام طلب عرض السعر. سنتواصل معك خلال 24 ساعة.',
    note: 'الجداول الزمنية نطاقات معتادة بعد جاهزية المحتوى. يؤكّد عرض السعر النطاق والتواريخ بدقة.',
  },
};

export const tools = { en, ar };
